title: Andreas Nicklaus
url: https://www.andreasnicklaus.de
baseurl: /
# twitter_username: andreasnicklaus
# github_username:  andreasnicklaus
footer_content: >
  Copyright &copy; 2024 Andreas Nicklaus. Distributed by an <a href=\"https://github.com/andreasnicklaus/andreasnicklaus.de/tree/main/LICENSE.txt\">MIT license.</a>
color_scheme: dark

# Build settings
theme: just-the-docs
plugins:
  - jekyll-relative-links
  - jekyll-sitemap

mermaid:
  version: "9.1.3"

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
