title: Andreas Nicklaus
url: https://www.andreasnicklaus.de
baseurl: /
color_scheme: dark

favicon_ico: "/img/favicon.ico"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-relative-links
  - jekyll-sitemap

callouts:
  custom:
    color: grey-dk

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
